#!/bin/python3

import math
import os
import random
import re
import sys



if __name__ == '__main__':
    n = int(input().strip())
    
    # determine if user value meets constraint
    if (n >= 2 and n <= 20):
        
        # create while loop to iterate through
             
        # so long as our iteration gets to 10 and then stops
        for i in range(1, 11):
            
            # create our result
            result = n * i
            
            print(n , "x" , i , "=" , result)
